// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC81StkyFSYPks5svV8p7BuLWQKkdXeXvo',
    appId: '1:570063531532:web:74501e3559bbf193b70829',
    messagingSenderId: '570063531532',
    projectId: 'pro-material-49447',
    authDomain: 'pro-material-49447.firebaseapp.com',
    databaseURL: 'https://pro-material-49447-default-rtdb.firebaseio.com',
    storageBucket: 'pro-material-49447.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNSsY166PAMWO4tfduoTORpnybfg_SKmU',
    appId: '1:570063531532:android:f1dbb70717078995b70829',
    messagingSenderId: '570063531532',
    projectId: 'pro-material-49447',
    databaseURL: 'https://pro-material-49447-default-rtdb.firebaseio.com',
    storageBucket: 'pro-material-49447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_-je6y04hBxESUVnYvI3n2oA-wWjyTs',
    appId: '1:570063531532:ios:580cff91fb0c5ab5b70829',
    messagingSenderId: '570063531532',
    projectId: 'pro-material-49447',
    databaseURL: 'https://pro-material-49447-default-rtdb.firebaseio.com',
    storageBucket: 'pro-material-49447.appspot.com',
    iosClientId: '570063531532-2b8cn8guqga82v2b964mb3k54m8ebf7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudMaterial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-_-je6y04hBxESUVnYvI3n2oA-wWjyTs',
    appId: '1:570063531532:ios:580cff91fb0c5ab5b70829',
    messagingSenderId: '570063531532',
    projectId: 'pro-material-49447',
    databaseURL: 'https://pro-material-49447-default-rtdb.firebaseio.com',
    storageBucket: 'pro-material-49447.appspot.com',
    iosClientId: '570063531532-2b8cn8guqga82v2b964mb3k54m8ebf7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudMaterial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC81StkyFSYPks5svV8p7BuLWQKkdXeXvo',
    appId: '1:570063531532:web:136023975715e5efb70829',
    messagingSenderId: '570063531532',
    projectId: 'pro-material-49447',
    authDomain: 'pro-material-49447.firebaseapp.com',
    databaseURL: 'https://pro-material-49447-default-rtdb.firebaseio.com',
    storageBucket: 'pro-material-49447.appspot.com',
  );
}
